# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desafio 2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desafio 2
  pod 'Alamofire', '~> 5.5'
  pod 'SDWebImageSwiftUI'

  target 'Desafio 2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Desafio 2UITests' do
    # Pods for testing
  end

end
